### ISSUE TITLE
Story book cannot be created 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/pcui-graph#34]
Ran 
```
npm install
npm run storybook
```

I get the following error:
```
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
WARN Failed to load static files, no such directory: /Users/syau/Snapchat/Dev/playcanvas-public/pcui-graph/public
WARN Make sure this directory exists, or omit the -s (--static-dir) option.
info Addon-docs: using MDX1
info => Using implicit CSS loaders
(node:77486) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
WARN Storybook support for Create React App is now a separate preset.
WARN To use the new preset, install `@storybook/preset-create-react-app` and add it to the list of `addons` in your `.storybook/main.js` config file.
WARN The built-in preset has been disabled in Storybook 6.0.
info => Using default Webpack4 setup
10% building 1/1 modules 0 active/Users/syau/Snapchat/Dev/playcanvas-public/pcui-graph/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13
    mainCompilation.fileSystemInfo.createSnapshot(
                                   ^

TypeError: Cannot read properties of undefined (reading 'createSnapshot')
    at /Users/syau/Snapchat/Dev/playcanvas-public/pcui-graph/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/Users/syau/Snapchat/Dev/playcanvas-public/pcui-graph/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /Users/syau/Snapchat/Dev/playcanvas-public/pcui-graph/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
```

Another forum user gets a different error (https://forum.playcanvas.com/t/introducing-pcui-graph-an-node-based-graph-rendering-library-for-the-web/21733/4?u=yaustar):  
```
10% building 1/3 modules 2 active /home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/addon-docs/preview.js-generated-config-entry.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/builder-webpack4/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/builder-webpack4/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /home/jay3d/Documents/Development/pcui-graph/node_modules/@storybook/builder-webpack4/node_modules/loader-runner/lib/LoaderRunner.js:205:4 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 1.
```

**Comment by yaustar** [comment]
CNR
